#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
int splash(int splash)
{

printf("                                                                                                                                                              .::\n");                                                                                                                                         
printf("                                                                                                                                                             -##*=:\n");                                                                                                                                         
printf("                                                                                                                                                           =oo+=.\n");                                                                                                                                           
printf("                                                                                                                                                          -oo#+\n");                                                                                                                                             
printf("                                                                                                                                                          -oo#*\n");                                                                                                                                             
printf("                                                                                                                                                           .+#*..\n");                                                                                                                                           
printf("                                                                                                                                                               :*oo-\n");                                                                                                                                        
printf("                                                                                                                                                                 #o+\n");                                                                                                                                        
printf("                                                                                                                   -*ooooo#+-.                                  -o*.\n");                                                                                                                                        
printf("                                                                                                                 .*oo#*+:  :=*#+: ..:::..                     -#*:\n");                                                                                                                                          
printf("                                                                                                                 -oo*#-        :**    ..:.:.               ..-- \n");                                                                                                                                            
printf("                                                                                                                 *ooo=           :-      .  .       ..-=+--. \n");                                                                                                                                               
printf("                                                                                                                 =ooo:          .=.:.  .....-=---===--:\n");                                                                                                                                                     
printf("                                                                                                                 .ooo:          ...-. .::.:. \n");                                                                                                                                                               
printf("                                                                                                                  =oo*        +=   .::.-..     .:=++*#####*=:\n");                                                                                                                                               
printf("                                                                                                                   =oo*.:::.-*o*o=.   .. .-+*oooooooooooooooo+ \n");                                                                                                                                             
printf("                                                                                                                   .=oooo##+*#==-=o##=:=*#***==++#o*+::-#oooo+\n");                                                                                                                                              
printf("                                                                                                                  .*ooooooo+*#+#=**+:   ...:-*ooo+#oo# .+ooo=                                                     .::=++++++-:.\n");                                                                             
printf("                                                                                                                 -ooooooooo*#oooooo.         .*ooo+*o--#o#=.                                                  -+ooooooooooooooooo*-\n");                                                                        
printf("                                                                                                                =ooo#oooooo=#ooo+oo:         =oo*=#o##+-.                                                  :*ooooooooooooooooooooooo+.\n");                                                                      
printf("                                                                                                              .==oo#oooooo=..:==ooo.       -*#+++*=-.                                                     -ooooooooooooooooooooooooooo+\n");                                                                     
printf("                                                                                                             +*=-=+oooo*:    .:*oo=       :::-=.                                                          oooooooooooooooooo#ooooooooooo.\n");                                                                   
printf("                                                                                                            .ooo+++++:.   .  :#ooo.  .-+*+**o**                                                           #oooooooooooooooooo#--#ooooooo#\n");                                                                  
printf("                                                                                                            =oooo++=-=-:    .*###: :#oo*#=*o*##.                                                          .#ooooooooooooooooooo: =ooooooo=\n");                                                                  
printf("                                                                                                            oooo=..-++--=.  .+-=-:-ooo=o**#oo=oo=                                                           :+ooooooooooooooooo#  +oooooo#\n");                                                                  
printf("                                                               .ooooooooooooooooooooooooooooooooooooooooooo*oooo.   .:+--= ..o--=ooooooo##oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*\n");                                                               
printf("                                                                 +oooooooooooooooooooooooooooooooooooooooooooooo.  . .#*+*: .+*-=ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo-\n");                                                             
printf("                                                                  .#oooooooooooooooooooooooooooooooooooooooooooo.   .. :=*#=-.-+#oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*.\n");                                                           
printf("                                                                    =ooooooooooooooooooooooooooooooooooooooooooo.       ..:=#=+oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.\n");                                                          
printf("                                                                            .=*oooooooooooooooooooo-     +oooooo.          .:::=ooooo**#+-..  *oo#+.     :*ooooooooooooo#oo*-+ooooooo.   -#ooooooooooooooooo   :+*oooooooo=      ooooooo*\n");                                                                   
printf("                                                                        .-*ooooooooooooooooooooooooo*    -oooooo           =*oooo*#ooooooooooooooo#o=       .:..:ooooooooooooooooooo#  :ooooooooooooooooooo=:*oooooooooooooo=.  =ooooooo-\n");                                                                   
printf("                                                                    :+oooooooooooooooooooooooooooooo=   #oooooo           oooooooooooooooooooooooooo=    .+o+   #oooooooooooooooooo- :oooooooooooooooooooooooooooooooooooooo#  #ooooooo\n");                                                                    
printf("                                                                  .=ooooooooooooooooooooooo#.=oooooooo. :ooooooo           o*ooooooooooooooooooooooooo: -#ooo= :oooooooooooooooooooo  oooooooooooooooooooooooooooooooooooooo=  :ooooooo=\n");                                                                    
printf("                                                                  .ooooooooooooo*- *oooooooooooooooooo. *ooooooo           -o+oooooooooooooooooooooooo#oooooo+#oooooooooooooooooooo+  ooooooooooooooooooooooooooooooooooooo:   oooooooo\n");                                                                     
printf("                                                                   .oooooooooooo#-.ooooooooooooooooooo  ooooooo*            +#*ooooooooooooooooooooooooooooooooooooooooo+. oooooooo.  =ooooooooo#=ooooooooooooooooooooooo#.   .ooooooo+\n");                                                                     
printf("                                                                     *ooooooooooooooooooooooooooooooo+ +ooooooo+:.:.....:.:.:+#*oooooooooooooooooooooooooooooooooooooo*.  .ooooooo*    .=*###*=. ooooooooooooo+.*ooooooo#     +ooooooo.\n");                                                                     
printf("                                                                      +ooooooooooooooooooooooooooooo*  ooooooo#:+--:+=::+-:--= =*ooooooooooooooooooooo=:oooooooooooo*.    +ooooooo:              ooooooooooo=. .ooooooo#.     ooooooo#\n");                                                                      
printf("                                                                         .:=*ooooooooooooooooooooo#:  -ooooooo-.*--:=* ==--:+=   +o##****-oo+ooooooooo- -ooooooooo*:     .oooooooo                +ooooooo=    =ooooooo:     =ooooooo:\n");                                                                      
printf("                                                                              =oooooooooo:-+###*-.    #ooooooo  *---+*.*-==-+.   ==-+...  .=#oooooooo#    .=+***-.       -ooooooo-                 :ooooo.     +oooooo*      oooooooo\n");                                                                       
printf("                                                                               .oooooooo#            :ooooooo+  *=--+*=*++--+  :***#*+***++**oooooooo.                   oooooooo                    =o#.     .ooooooo.     :ooooooo=\n");                                                                       
printf("                                                                                 ooooooo-            *ooooooo.  +=--+*-**---=  :+=+*++**++=--+ooooo+             .-+**#++ooooooo+                              ooooooo      *ooooooo \n");                                                                       
printf("                                                                                 =oooooo            .ooooooo*   +=-:*++*-::+:  =-+*#=.       -*-:.             -#ooooooooooooooo.                              oooooo#      ooooooo*\n");                                                                        
printf("                                                                                 .ooooo+             +oooooo:   +*--+ooo***#+:-+ooooo+        =+              #oooooooooooooooo#                               oooooo+      .oooooo:\n");                                                                        
printf("                                                                                  .#ooo.              :ooooo    -o##o#oo#ooooo#+#oooo+...     .+*+=.         +oooooooooooooooooo-                              :+oooo+       .+ooo#\n");                                                                        
printf("                                                                                    :o*                 *oo=      =*#ooo:  .-*=-:+*+-::.:.:-::+ooooo-        *ooooooooooooooooooo#                                .-*-         :oo-\n");                                                                        
printf("                                                                                                         -o                 :+:-::.:.        .#ooooo=        :ooooooooooooooooooooo.                                             - \n");                                                                         
printf("                                                                                                                           .=:                 *ooo+           =#oooooo#+: =ooooooo#\n");                                                                                                                        
printf("                                                                                                                            .                                      .         +oooooo\n");                                                                                                                        
printf("                                                                                                                                                                              -oooo+\n");                                                                                                                        
printf("                                                                                                                                                                                ::.\n");                                                                                                                        
printf("                                                                                                                                                                                                                                   :-:\n");                                                                      
printf("                                                                                                                                                                                                  **-=                            #o=-----+*= \n");                                                              
printf("                                                                                                                                                                        .=*+***++++++*#++*+**#++****+#*+++o#**+++++*#*++#o**.  .=+oo=++======+=+##+-:==-\n");                                                   
printf("                                                                                                                                                                           *o=. .-+*#oo. :o#- .  =oo.oo. :oo  :=+**oo   #o:      .oo  =*#*=:=*=-o#  *++*\n");                                                  
printf("                                                                                                                                                                          +o  .:+*+=.#o  o*   -+:--=+oo:  oo :+*+-.oo   +o:       oo oo-++:*o*  o#  ==== \n");                                                   
printf("                                                                                                                                                                           =-oo+ -= :+*-=-+=oo+#*-**=:oo=+##-=.== :+*-=.=#==:     +o.+-=++. :.  ##-===+#=.\n");                                                  
printf("                                                                                                                                                                                                  ...:....                          .\n");                       



    return splash;
}